networks:
  share-net-vllm:
    name: share-net-vllm
    attachable: true

services:    
  vllm:
    container_name: vllm-amd
    image: rocm/vllm-dev:preview_releases_rocm_v0.16.0_20260212

    # amd gpu
    runtime: amd
    environment:
      - AMD_VISIBLE_DEVICES=all

    shm_size: 16g
    volumes:
      - /data/volumes-data/models/huggingface:/root/.cache/huggingface

    tty: true
    restart: unless-stopped

    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - share-net-vllm

volumes:
  vllm:
