networks:
  share-net-vllm:
    name: share-net-vllm
    attachable: true


services:    
  vllm:
    container_name: vllm-amd
    image: rocm/vllm:v0.14.0_amd_dev

    # amd gpu
    runtime: amd
    environment:
      - AMD_VISIBLE_DEVICES=all
      - VLLM_USE_MODELSCOPE=True

    shm_size: 16g
    volumes:
      - /data/volumes-data/vllm/root/.cache:/root/.cache

    tty: true
    restart: unless-stopped

    dns:
      - 1.1.1.1
      - 8.8.8.8
    networks:
      - share-net-vllm

volumes:
  vllm:
